language: go
go:
- "1.5"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=zhouree/gohttp
notifications:
  email:
    recipients:
    - zhouree@163.com
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
