language: go
go:
- "1.6"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=julor/go-proj-4
notifications:
  email:
    recipients:
    - julor@qq.com
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
