language: go
go:
- "1.5"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=jesusrmoreno/uuid-service
notifications:
  email:
    recipients:
    - jesus.r.moreno.16@dartmouth.edu
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
