language: go
go:
- "1.5"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=everfore/codeload
notifications:
  email:
    recipients:
    - shaalx@yahoo.com.sg
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
