language: go
go:
- "1.6"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=Albert-Boy/Go
notifications:
  email:
    recipients:
    - albert.wong.chn@gmail.com
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
