language: go
go:
- "1.5"
env:
  global:
  - GIT_BRANCH=
  - GITHUB_REPO=alex-ant/spl
notifications:
  email:
    recipients:
    - alex.ant0303@gmail.com
    on_success: always
    on_failure: always
before_install: []
script:
- bash build.sh
after_success:
- echo done
