language: go
go:
- "1.5"
env:
  global:
  - GIT_BRANCH=master
  - GITHUB_REPO=tools/godep
notifications:
  email:
    recipients:
    - codeskyblue@gmail.com
    on_success: always
    on_failure: always
before_install: []
script:
- sed -n '340,355p' /home/travis/build.sh
- bash build.sh
after_success: []
